version: '3.8'

services:
  mongo:
    image: mongo:4.2
    volumes:
      - ./data/data-mongo-cypress:/data/db
    ports:
      - 27017:27017
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'

      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
      MINIO_ENDPOINT: 'storage'
      MINIO_URL: 'http://storage'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress

    ports:
      - 1234:1234
    depends_on:
      - mongo
      - storage

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
    ports:
      - 4000:4000
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 80:8080
    depends_on:
      - mongo
      - api

  storage:
    image: minio/minio
    hostname: 'storage'
    privileged: true
    environment:
      MINIO_ACCESS_KEY: 'MW32h3gd6HvjBEgTRx'
      MINIO_SECRET_KEY: 't6NgQWUcEyG2AzaDCVkN6sbWcvDCVkN6sGiZ7'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
        
  jenkins:
    container_name: jenkins
    image: 'jenkinsci/blueocean:latest'
    ports:
      - '8080:8080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - 'npm-cache:/root/.npm'
      - 'cypress-cache:/root/.cache'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=8443'

  # editor:
  #  image: 'mgsousa/go-jenkins-editor:latest'
  #  ports:
  #    - '8088:8088'
  #  command: -jenkinsUrl http://jenkins:8080 -port 8088
  # environment:
  #    JENKINS_ADMIN_USERNAME: "$JENKINS_ADMIN_USERNAME"
  #   JENKINS_ADMIN_API_TOKEN: "$JENKINS_ADMIN_API_TOKEN"
  #  depends_on: {
  #    "jenkins": {
  #      "condition": "service_healthy"
  #    }
  #  }
  
volumes:
  jenkins_data:
    driver: local
  npm-cache:
  cypress-cache: